[workspace]
"resolver" = "3"
members = ["api", "sol"]

[workspace.dependencies]
actix-web = "4"
solana-sdk = "2.3.0"
solana-client = {version = "2"}
sol = {path = "./sol"}
dotenv = "0.15.0"
spl-token = "8"